package CashDance.Bot.service;

public enum MenuButtons {
    CANCEL,
    MAINMENU_MYCASHBACK,
    MAINMENU_MYCARDS,
    MAINMENU_MYCATEGORIES,
    CARDSMENU_ALLMYCARDS,
    CARDSMENU_NEWCARD,
    CARDSMENU_EDITCARD,
    CARDSMENU_DELETECARD,
    CATMENU_NEWCAT,
    CATMENU_MYCATS,
    CATMENU_EDITCAT,
    CATMENU_DELETECAT,
    ALLMENU_TOMAINMENU,
    CARDSMENU_EDITCARD_ANYCARD,
    CARDSMENU_DELETECARD_ANYCARD,
    CHOICEMENU_YES,
    CHOICEMENU_NO,
    CHANCES_ACTCHANCES_CAT,
    CHANCESMENU_NEWCHANCE,
    CHANCESMENU_EDITCHANCE,
    CHANCESMENU_DELETECHANCE,

    CARDSMENU_ANYCARD, CARDSMENU_ALLMYCARDS_ANYCARD, NEWCHANCE_ANYCARD, NEWCHANCE_ANYCAT, NEWCHANCE_PERCENT, EDITCHANCE_ANYCARD, EDITCHANCE_ANYCHANCE, DELETECHANCE_ANYCARD, CHANCES_ACTCHANCES_CARD, ACTCHANCES_CAT_CHOSEN, ACTCHANCES_CARD_CHOSEN, CATEGORIESMENU_ALLCATS, CATMENU_EDITCAT_ANYCAT, CATMENU_DELETECAT_ANYCAT;


}
