package CashDance.Bot.service;

public enum MenuButtons {
    MAINMENU_MYCASHBACK,
    MAINMENU_MYCARDS,
    MAINMENU_MYCATEGORIES,
    CARDSMENU_MYCARDS,
    CARDSMENU_NEWCARD,
    CARDSMENU_EDITCARD,
    CARDSMENU_DELETECARD,
    CATEGORIESMENU_MYCARDS,
    CATEGORIESMENU_NEWCARD,
    CATEGORIESMENU_MYCATEGORIES,
    CATEGORIESMENU_EDITCATEGORY,
    CATEGORIESMENU_DELETECATEGORY,
    ALLMENU_TOMAINMENU,
    CARDSMENU_EDITCARD_ANYCARD,
    CARDSMENU_DELETECARD_ANYCARD, CHOICEMENU_YES, CHOICEMENU_NO;


}
