package CashDance.Bot.service;

public enum MenuButtons {
    MAINMENU_MYCASHBACK,
    MAINMENU_MYCARDS,
    MAINMENU_MYCATEGORIES, CARDSNMENU_MYCARDS, CARDSMENU_NEWCARD, CARDSMENU_EDITCARD, CARDSMENU_DELETECARD, CATEGORIESMENU_MYCARDS, CATEGORIESMENU_NEWCARD, CATEGORIESMENU_MYCATEGORIES, CATEGORIESMENU_EDITCATEGORY, CATEGORIESMENU_DELETECATEGORY, ALLMENU_TOMAINMENU;


}
