package CashDance.Bot.service;

public enum ServiceState {
    DEFAULT_STATE,
    NEW_BANK_CARD__AWAITING_BANK_NAME,
    NEW_BANK_CARD__AWAITING_BANK_CARD_NAME,
    NEW_CHANCE__AWAITING_BANK_CARD_ID,
    NEW_CHANCE__AWAITING_CATEGORY_ID,
    ALL_CHANCES__AWAITING_CATEGORY_ID, NEW_CHANCE__AWAITING_RATE



}
